export const browserCoreExamples = [
  "surprisebot browser status",
  "surprisebot browser start",
  "surprisebot browser stop",
  "surprisebot browser tabs",
  "surprisebot browser open https://example.com",
  "surprisebot browser focus abcd1234",
  "surprisebot browser close abcd1234",
  "surprisebot browser screenshot",
  "surprisebot browser screenshot --full-page",
  "surprisebot browser screenshot --ref 12",
  "surprisebot browser snapshot",
  "surprisebot browser snapshot --format aria --limit 200",
  "surprisebot browser snapshot --efficient",
  "surprisebot browser snapshot --labels",
];

export const browserActionExamples = [
  "surprisebot browser navigate https://example.com",
  "surprisebot browser resize 1280 720",
  "surprisebot browser click 12 --double",
  'surprisebot browser type 23 "hello" --submit',
  "surprisebot browser press Enter",
  "surprisebot browser hover 44",
  "surprisebot browser drag 10 11",
  "surprisebot browser select 9 OptionA OptionB",
  "surprisebot browser upload /tmp/file.pdf",
  'surprisebot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "surprisebot browser dialog --accept",
  'surprisebot browser wait --text "Done"',
  "surprisebot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "surprisebot browser console --level error",
  "surprisebot browser pdf",
];
